<a href="https://colab.research.google.com/github/MohanPatil1/DS-And-DA-Assignments/blob/main/Feature_Engineering_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Univariate Feature selection

In [1]:
# Out of 8 features of dataset which one is most important in predicting class?
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
# load data, patients details taken ,Identify which variable is most important
filename='/content/pima-indians-diabetes.data.csv'
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)
array =dataframe.values
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [3]:
X = array[:,0:8]
Y = array[:,8] # Separate them in X and Y

# Feature extraction
test =SelectKBest(score_func=chi2,k=5)
fit=test.fit(X,Y)

set_printoptions(precision=4)
print(fit.scores_) # will get chi square for each feature
features = fit.transform(X)

[ 111.5197 1411.887    17.6054   53.108  2175.5653  127.6693    5.3927
  181.3037]


In [4]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [5]:
type(test)

sklearn.feature_selection._univariate_selection.SelectKBest

In [7]:
x= pd.DataFrame(fit.scores_).T # T will transpose list into dataframe
x

0            1          2  ...           5         6           7
0  111.519691  1411.887041  17.605373  ...  127.669343  5.392682  181.303689

[1 rows x 8 columns]

In [9]:
x.columns=names[:8]
x

preg         plas       pres  ...        mass      pedi         age
0  111.519691  1411.887041  17.605373  ...  127.669343  5.392682  181.303689

[1 rows x 8 columns]

In [10]:
dataframe

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

# Feature Scaling (Standardization and Normalization

## Recursive Feature Elimination

In [11]:
# feature Extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load data, patients details taken ,Identify which variable is most important
filename='/content/pima-indians-diabetes.data.csv'
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)
array =dataframe.values
X = array[:,0:8]
Y = array[:,8] # Separate them in X and Y

# Feature extraction
model = LogisticRegression(max_iter=400)

rfe =RFE(model)# see best 3 feature
fit =rfe.fit(X,Y)

In [12]:
# Num features: top 4 features are available
fit.n_features_

4

In [13]:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [14]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [16]:
# feature ranking
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

In [17]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

# Feature importance Using Decision Tree

In [18]:
# feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier
# load data, patients details taken ,Identify which variable is most important
filename='/content/pima-indians-diabetes.data.csv'
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)
array =dataframe.values
X = array[:,0:8]
Y = array[:,8] # Separate them in X and Y

# Feature extraction
model = DecisionTreeClassifier()
model.fit(X,Y)
print(model.feature_importances_) # feature importance score

[0.058  0.3237 0.1124 0.02   0.0279 0.231  0.1138 0.1132]


In [19]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']